const express = require ('express');
const app = express ();
const server = require ('http').Server (app);
const bodyParser = require ('body-parser');

// For parsing JSON
app.use (bodyParser.json ());

app.use (function (req, res, next) {
  res.header ('Access-Control-Allow-Origin', '*');
  res.header (
    'Access-Control-Allow-Headers',
    'Origin, X-Requested-With, Content-Type, Accept'
  );
  next ();
});

// // Send the file with socket config
// app.get ('/', (req, res) => {
//   res.set ('Access-Control-Allow-Origin', '*');
//   res.sendFile (__dirname + '/index.html');
// });

// const graphData = {
//   nodes: [
//     {id: 'Myriel', group: 1},
//     {id: 'Napoleon', group: 1},
//     {id: 'Mlle.Baptistine', group: 1},
//     {id: 'Mme.Magloire', group: 1},
//     {id: 'CountessdeLo', group: 1},
//     {id: 'Geborand', group: 1},
//     {id: 'Champtercier', group: 1},
//     {id: 'Cravatte', group: 1},
//     {id: 'Count', group: 1},
//     {id: 'OldMan', group: 1},
//     {id: 'Labarre', group: 2},
//     {id: 'Valjean', group: 2},
//     {id: 'Marguerite', group: 3},
//     {id: 'Mme.deR', group: 2},
//     {id: 'Isabeau', group: 2},
//     {id: 'Gervais', group: 2},
//     {id: 'Tholomyes', group: 3},
//     {id: 'Listolier', group: 3},
//     {id: 'Fameuil', group: 3},
//     {id: 'Blacheville', group: 3},
//     {id: 'Favourite', group: 3},
//     {id: 'Dahlia', group: 3},
//     {id: 'Zephine', group: 3},
//     {id: 'Fantine', group: 3},
//     {id: 'Mme.Thenardier', group: 4},
//     {id: 'Thenardier', group: 4},
//     {id: 'Cosette', group: 5},
//     {id: 'Javert', group: 4},
//     {id: 'Fauchelevent', group: 0},
//     {id: 'Bamatabois', group: 2},
//     {id: 'Perpetue', group: 3},
//     {id: 'Simplice', group: 2},
//     {id: 'Scaufflaire', group: 2},
//     {id: 'Woman1', group: 2},
//     {id: 'Judge', group: 2},
//     {id: 'Champmathieu', group: 2},
//     {id: 'Brevet', group: 2},
//     {id: 'Chenildieu', group: 2},
//     {id: 'Cochepaille', group: 2},
//     {id: 'Pontmercy', group: 4},
//     {id: 'Boulatruelle', group: 6},
//     {id: 'Eponine', group: 4},
//     {id: 'Anzelma', group: 4},
//     {id: 'Woman2', group: 5},
//     {id: 'MotherInnocent', group: 0},
//     {id: 'Gribier', group: 0},
//     {id: 'Jondrette', group: 7},
//     {id: 'Mme.Burgon', group: 7},
//     {id: 'Gavroche', group: 8},
//     {id: 'Gillenormand', group: 5},
//     {id: 'Magnon', group: 5},
//     {id: 'Mlle.Gillenormand', group: 5},
//     {id: 'Mme.Pontmercy', group: 5},
//     {id: 'Mlle.Vaubois', group: 5},
//     {id: 'Lt.Gillenormand', group: 5},
//     {id: 'Marius', group: 8},
//     {id: 'BaronessT', group: 5},
//     {id: 'Mabeuf', group: 8},
//     {id: 'Enjolras', group: 8},
//     {id: 'Combeferre', group: 8},
//     {id: 'Prouvaire', group: 8},
//     {id: 'Feuilly', group: 8},
//     {id: 'Courfeyrac', group: 8},
//     {id: 'Bahorel', group: 8},
//     {id: 'Bossuet', group: 8},
//     {id: 'Joly', group: 8},
//     {id: 'Grantaire', group: 8},
//     {id: 'MotherPlutarch', group: 9},
//     {id: 'Gueulemer', group: 4},
//     {id: 'Babet', group: 4},
//     {id: 'Claquesous', group: 4},
//     {id: 'Montparnasse', group: 4},
//     {id: 'Toussaint', group: 5},
//     {id: 'Child1', group: 10},
//     {id: 'Child2', group: 10},
//     {id: 'Brujon', group: 4},
//     {id: 'Mme.Hucheloup', group: 8},
//   ],
//   links: [
//     {source: 'Napoleon', target: 'Myriel', value: 1},
//     {source: 'Mlle.Baptistine', target: 'Myriel', value: 8},
//     {source: 'Mme.Magloire', target: 'Myriel', value: 10},
//     {source: 'Mme.Magloire', target: 'Mlle.Baptistine', value: 6},
//     {source: 'CountessdeLo', target: 'Myriel', value: 1},
//     {source: 'Geborand', target: 'Myriel', value: 1},
//     {source: 'Champtercier', target: 'Myriel', value: 1},
//     {source: 'Cravatte', target: 'Myriel', value: 1},
//     {source: 'Count', target: 'Myriel', value: 2},
//     {source: 'OldMan', target: 'Myriel', value: 1},
//     {source: 'Valjean', target: 'Labarre', value: 1},
//     {source: 'Valjean', target: 'Mme.Magloire', value: 3},
//     {source: 'Valjean', target: 'Mlle.Baptistine', value: 3},
//     {source: 'Valjean', target: 'Myriel', value: 5},
//     {source: 'Marguerite', target: 'Valjean', value: 1},
//     {source: 'Mme.deR', target: 'Valjean', value: 1},
//     {source: 'Isabeau', target: 'Valjean', value: 1},
//     {source: 'Gervais', target: 'Valjean', value: 1},
//     {source: 'Listolier', target: 'Tholomyes', value: 4},
//     {source: 'Fameuil', target: 'Tholomyes', value: 4},
//     {source: 'Fameuil', target: 'Listolier', value: 4},
//     {source: 'Blacheville', target: 'Tholomyes', value: 4},
//     {source: 'Blacheville', target: 'Listolier', value: 4},
//     {source: 'Blacheville', target: 'Fameuil', value: 4},
//     {source: 'Favourite', target: 'Tholomyes', value: 3},
//     {source: 'Favourite', target: 'Listolier', value: 3},
//     {source: 'Favourite', target: 'Fameuil', value: 3},
//     {source: 'Favourite', target: 'Blacheville', value: 4},
//     {source: 'Dahlia', target: 'Tholomyes', value: 3},
//     {source: 'Dahlia', target: 'Listolier', value: 3},
//     {source: 'Dahlia', target: 'Fameuil', value: 3},
//     {source: 'Dahlia', target: 'Blacheville', value: 3},
//     {source: 'Dahlia', target: 'Favourite', value: 5},
//     {source: 'Zephine', target: 'Tholomyes', value: 3},
//     {source: 'Zephine', target: 'Listolier', value: 3},
//     {source: 'Zephine', target: 'Fameuil', value: 3},
//     {source: 'Zephine', target: 'Blacheville', value: 3},
//     {source: 'Zephine', target: 'Favourite', value: 4},
//     {source: 'Zephine', target: 'Dahlia', value: 4},
//     {source: 'Fantine', target: 'Tholomyes', value: 3},
//     {source: 'Fantine', target: 'Listolier', value: 3},
//     {source: 'Fantine', target: 'Fameuil', value: 3},
//     {source: 'Fantine', target: 'Blacheville', value: 3},
//     {source: 'Fantine', target: 'Favourite', value: 4},
//     {source: 'Fantine', target: 'Dahlia', value: 4},
//     {source: 'Fantine', target: 'Zephine', value: 4},
//     {source: 'Fantine', target: 'Marguerite', value: 2},
//     {source: 'Fantine', target: 'Valjean', value: 9},
//     {source: 'Mme.Thenardier', target: 'Fantine', value: 2},
//     {source: 'Mme.Thenardier', target: 'Valjean', value: 7},
//     {source: 'Thenardier', target: 'Mme.Thenardier', value: 13},
//     {source: 'Thenardier', target: 'Fantine', value: 1},
//     {source: 'Thenardier', target: 'Valjean', value: 12},
//     {source: 'Cosette', target: 'Mme.Thenardier', value: 4},
//     {source: 'Cosette', target: 'Valjean', value: 31},
//     {source: 'Cosette', target: 'Tholomyes', value: 1},
//     {source: 'Cosette', target: 'Thenardier', value: 1},
//     {source: 'Javert', target: 'Valjean', value: 17},
//     {source: 'Javert', target: 'Fantine', value: 5},
//     {source: 'Javert', target: 'Thenardier', value: 5},
//     {source: 'Javert', target: 'Mme.Thenardier', value: 1},
//     {source: 'Javert', target: 'Cosette', value: 1},
//     {source: 'Fauchelevent', target: 'Valjean', value: 8},
//     {source: 'Fauchelevent', target: 'Javert', value: 1},
//     {source: 'Bamatabois', target: 'Fantine', value: 1},
//     {source: 'Bamatabois', target: 'Javert', value: 1},
//     {source: 'Bamatabois', target: 'Valjean', value: 2},
//     {source: 'Perpetue', target: 'Fantine', value: 1},
//     {source: 'Simplice', target: 'Perpetue', value: 2},
//     {source: 'Simplice', target: 'Valjean', value: 3},
//     {source: 'Simplice', target: 'Fantine', value: 2},
//     {source: 'Simplice', target: 'Javert', value: 1},
//     {source: 'Scaufflaire', target: 'Valjean', value: 1},
//     {source: 'Woman1', target: 'Valjean', value: 2},
//     {source: 'Woman1', target: 'Javert', value: 1},
//     {source: 'Judge', target: 'Valjean', value: 3},
//     {source: 'Judge', target: 'Bamatabois', value: 2},
//     {source: 'Champmathieu', target: 'Valjean', value: 3},
//     {source: 'Champmathieu', target: 'Judge', value: 3},
//     {source: 'Champmathieu', target: 'Bamatabois', value: 2},
//     {source: 'Brevet', target: 'Judge', value: 2},
//     {source: 'Brevet', target: 'Champmathieu', value: 2},
//     {source: 'Brevet', target: 'Valjean', value: 2},
//     {source: 'Brevet', target: 'Bamatabois', value: 1},
//     {source: 'Chenildieu', target: 'Judge', value: 2},
//     {source: 'Chenildieu', target: 'Champmathieu', value: 2},
//     {source: 'Chenildieu', target: 'Brevet', value: 2},
//     {source: 'Chenildieu', target: 'Valjean', value: 2},
//     {source: 'Chenildieu', target: 'Bamatabois', value: 1},
//     {source: 'Cochepaille', target: 'Judge', value: 2},
//     {source: 'Cochepaille', target: 'Champmathieu', value: 2},
//     {source: 'Cochepaille', target: 'Brevet', value: 2},
//     {source: 'Cochepaille', target: 'Chenildieu', value: 2},
//     {source: 'Cochepaille', target: 'Valjean', value: 2},
//     {source: 'Cochepaille', target: 'Bamatabois', value: 1},
//     {source: 'Pontmercy', target: 'Thenardier', value: 1},
//     {source: 'Boulatruelle', target: 'Thenardier', value: 1},
//     {source: 'Eponine', target: 'Mme.Thenardier', value: 2},
//     {source: 'Eponine', target: 'Thenardier', value: 3},
//     {source: 'Anzelma', target: 'Eponine', value: 2},
//     {source: 'Anzelma', target: 'Thenardier', value: 2},
//     {source: 'Anzelma', target: 'Mme.Thenardier', value: 1},
//     {source: 'Woman2', target: 'Valjean', value: 3},
//     {source: 'Woman2', target: 'Cosette', value: 1},
//     {source: 'Woman2', target: 'Javert', value: 1},
//     {source: 'MotherInnocent', target: 'Fauchelevent', value: 3},
//     {source: 'MotherInnocent', target: 'Valjean', value: 1},
//     {source: 'Gribier', target: 'Fauchelevent', value: 2},
//     {source: 'Mme.Burgon', target: 'Jondrette', value: 1},
//     {source: 'Gavroche', target: 'Mme.Burgon', value: 2},
//     {source: 'Gavroche', target: 'Thenardier', value: 1},
//     {source: 'Gavroche', target: 'Javert', value: 1},
//     {source: 'Gavroche', target: 'Valjean', value: 1},
//     {source: 'Gillenormand', target: 'Cosette', value: 3},
//     {source: 'Gillenormand', target: 'Valjean', value: 2},
//     {source: 'Magnon', target: 'Gillenormand', value: 1},
//     {source: 'Magnon', target: 'Mme.Thenardier', value: 1},
//     {source: 'Mlle.Gillenormand', target: 'Gillenormand', value: 9},
//     {source: 'Mlle.Gillenormand', target: 'Cosette', value: 2},
//     {source: 'Mlle.Gillenormand', target: 'Valjean', value: 2},
//     {source: 'Mme.Pontmercy', target: 'Mlle.Gillenormand', value: 1},
//     {source: 'Mme.Pontmercy', target: 'Pontmercy', value: 1},
//     {source: 'Mlle.Vaubois', target: 'Mlle.Gillenormand', value: 1},
//     {source: 'Lt.Gillenormand', target: 'Mlle.Gillenormand', value: 2},
//     {source: 'Lt.Gillenormand', target: 'Gillenormand', value: 1},
//     {source: 'Lt.Gillenormand', target: 'Cosette', value: 1},
//     {source: 'Marius', target: 'Mlle.Gillenormand', value: 6},
//     {source: 'Marius', target: 'Gillenormand', value: 12},
//     {source: 'Marius', target: 'Pontmercy', value: 1},
//     {source: 'Marius', target: 'Lt.Gillenormand', value: 1},
//     {source: 'Marius', target: 'Cosette', value: 21},
//     {source: 'Marius', target: 'Valjean', value: 19},
//     {source: 'Marius', target: 'Tholomyes', value: 1},
//     {source: 'Marius', target: 'Thenardier', value: 2},
//     {source: 'Marius', target: 'Eponine', value: 5},
//     {source: 'Marius', target: 'Gavroche', value: 4},
//     {source: 'BaronessT', target: 'Gillenormand', value: 1},
//     {source: 'BaronessT', target: 'Marius', value: 1},
//     {source: 'Mabeuf', target: 'Marius', value: 1},
//     {source: 'Mabeuf', target: 'Eponine', value: 1},
//     {source: 'Mabeuf', target: 'Gavroche', value: 1},
//     {source: 'Enjolras', target: 'Marius', value: 7},
//     {source: 'Enjolras', target: 'Gavroche', value: 7},
//     {source: 'Enjolras', target: 'Javert', value: 6},
//     {source: 'Enjolras', target: 'Mabeuf', value: 1},
//     {source: 'Enjolras', target: 'Valjean', value: 4},
//     {source: 'Combeferre', target: 'Enjolras', value: 15},
//     {source: 'Combeferre', target: 'Marius', value: 5},
//     {source: 'Combeferre', target: 'Gavroche', value: 6},
//     {source: 'Combeferre', target: 'Mabeuf', value: 2},
//     {source: 'Prouvaire', target: 'Gavroche', value: 1},
//     {source: 'Prouvaire', target: 'Enjolras', value: 4},
//     {source: 'Prouvaire', target: 'Combeferre', value: 2},
//     {source: 'Feuilly', target: 'Gavroche', value: 2},
//     {source: 'Feuilly', target: 'Enjolras', value: 6},
//     {source: 'Feuilly', target: 'Prouvaire', value: 2},
//     {source: 'Feuilly', target: 'Combeferre', value: 5},
//     {source: 'Feuilly', target: 'Mabeuf', value: 1},
//     {source: 'Feuilly', target: 'Marius', value: 1},
//     {source: 'Courfeyrac', target: 'Marius', value: 9},
//     {source: 'Courfeyrac', target: 'Enjolras', value: 17},
//     {source: 'Courfeyrac', target: 'Combeferre', value: 13},
//     {source: 'Courfeyrac', target: 'Gavroche', value: 7},
//     {source: 'Courfeyrac', target: 'Mabeuf', value: 2},
//     {source: 'Courfeyrac', target: 'Eponine', value: 1},
//     {source: 'Courfeyrac', target: 'Feuilly', value: 6},
//     {source: 'Courfeyrac', target: 'Prouvaire', value: 3},
//     {source: 'Bahorel', target: 'Combeferre', value: 5},
//     {source: 'Bahorel', target: 'Gavroche', value: 5},
//     {source: 'Bahorel', target: 'Courfeyrac', value: 6},
//     {source: 'Bahorel', target: 'Mabeuf', value: 2},
//     {source: 'Bahorel', target: 'Enjolras', value: 4},
//     {source: 'Bahorel', target: 'Feuilly', value: 3},
//     {source: 'Bahorel', target: 'Prouvaire', value: 2},
//     {source: 'Bahorel', target: 'Marius', value: 1},
//     {source: 'Bossuet', target: 'Marius', value: 5},
//     {source: 'Bossuet', target: 'Courfeyrac', value: 12},
//     {source: 'Bossuet', target: 'Gavroche', value: 5},
//     {source: 'Bossuet', target: 'Bahorel', value: 4},
//     {source: 'Bossuet', target: 'Enjolras', value: 10},
//     {source: 'Bossuet', target: 'Feuilly', value: 6},
//     {source: 'Bossuet', target: 'Prouvaire', value: 2},
//     {source: 'Bossuet', target: 'Combeferre', value: 9},
//     {source: 'Bossuet', target: 'Mabeuf', value: 1},
//     {source: 'Bossuet', target: 'Valjean', value: 1},
//     {source: 'Joly', target: 'Bahorel', value: 5},
//     {source: 'Joly', target: 'Bossuet', value: 7},
//     {source: 'Joly', target: 'Gavroche', value: 3},
//     {source: 'Joly', target: 'Courfeyrac', value: 5},
//     {source: 'Joly', target: 'Enjolras', value: 5},
//     {source: 'Joly', target: 'Feuilly', value: 5},
//     {source: 'Joly', target: 'Prouvaire', value: 2},
//     {source: 'Joly', target: 'Combeferre', value: 5},
//     {source: 'Joly', target: 'Mabeuf', value: 1},
//     {source: 'Joly', target: 'Marius', value: 2},
//     {source: 'Grantaire', target: 'Bossuet', value: 3},
//     {source: 'Grantaire', target: 'Enjolras', value: 3},
//     {source: 'Grantaire', target: 'Combeferre', value: 1},
//     {source: 'Grantaire', target: 'Courfeyrac', value: 2},
//     {source: 'Grantaire', target: 'Joly', value: 2},
//     {source: 'Grantaire', target: 'Gavroche', value: 1},
//     {source: 'Grantaire', target: 'Bahorel', value: 1},
//     {source: 'Grantaire', target: 'Feuilly', value: 1},
//     {source: 'Grantaire', target: 'Prouvaire', value: 1},
//     {source: 'MotherPlutarch', target: 'Mabeuf', value: 3},
//     {source: 'Gueulemer', target: 'Thenardier', value: 5},
//     {source: 'Gueulemer', target: 'Valjean', value: 1},
//     {source: 'Gueulemer', target: 'Mme.Thenardier', value: 1},
//     {source: 'Gueulemer', target: 'Javert', value: 1},
//     {source: 'Gueulemer', target: 'Gavroche', value: 1},
//     {source: 'Gueulemer', target: 'Eponine', value: 1},
//     {source: 'Babet', target: 'Thenardier', value: 6},
//     {source: 'Babet', target: 'Gueulemer', value: 6},
//     {source: 'Babet', target: 'Valjean', value: 1},
//     {source: 'Babet', target: 'Mme.Thenardier', value: 1},
//     {source: 'Babet', target: 'Javert', value: 2},
//     {source: 'Babet', target: 'Gavroche', value: 1},
//     {source: 'Babet', target: 'Eponine', value: 1},
//     {source: 'Claquesous', target: 'Thenardier', value: 4},
//     {source: 'Claquesous', target: 'Babet', value: 4},
//     {source: 'Claquesous', target: 'Gueulemer', value: 4},
//     {source: 'Claquesous', target: 'Valjean', value: 1},
//     {source: 'Claquesous', target: 'Mme.Thenardier', value: 1},
//     {source: 'Claquesous', target: 'Javert', value: 1},
//     {source: 'Claquesous', target: 'Eponine', value: 1},
//     {source: 'Claquesous', target: 'Enjolras', value: 1},
//     {source: 'Montparnasse', target: 'Javert', value: 1},
//     {source: 'Montparnasse', target: 'Babet', value: 2},
//     {source: 'Montparnasse', target: 'Gueulemer', value: 2},
//     {source: 'Montparnasse', target: 'Claquesous', value: 2},
//     {source: 'Montparnasse', target: 'Valjean', value: 1},
//     {source: 'Montparnasse', target: 'Gavroche', value: 1},
//     {source: 'Montparnasse', target: 'Eponine', value: 1},
//     {source: 'Montparnasse', target: 'Thenardier', value: 1},
//     {source: 'Toussaint', target: 'Cosette', value: 2},
//     {source: 'Toussaint', target: 'Javert', value: 1},
//     {source: 'Toussaint', target: 'Valjean', value: 1},
//     {source: 'Child1', target: 'Gavroche', value: 2},
//     {source: 'Child2', target: 'Gavroche', value: 2},
//     {source: 'Child2', target: 'Child1', value: 3},
//     {source: 'Brujon', target: 'Babet', value: 3},
//     {source: 'Brujon', target: 'Gueulemer', value: 3},
//     {source: 'Brujon', target: 'Thenardier', value: 3},
//     {source: 'Brujon', target: 'Gavroche', value: 1},
//     {source: 'Brujon', target: 'Eponine', value: 1},
//     {source: 'Brujon', target: 'Claquesous', value: 1},
//     {source: 'Brujon', target: 'Montparnasse', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Bossuet', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Joly', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Grantaire', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Bahorel', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Courfeyrac', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Gavroche', value: 1},
//     {source: 'Mme.Hucheloup', target: 'Enjolras', value: 1},
//   ],
// };

// group => sub cluster
// value: 79.1,
// },
//     {
//       source: 148,
//       target: 50,
//       value: 83.5,
//     },
//     {
//       source: 149,
//       target: 50,
//       value: 80.3,
//     },
//     {
//       source: 150,
//       target: 50,
//             const graphData = {
//               nodes: [
//                 {id: 69, group: 50},
//                 {id: 70, group: 50},
//                 {id: 71, group: 50},
//                 {id: 73, group: 50},
//                 {id: 74, group: 50},
//                 {id: 145, group: 50},
//                 {id: 146, group: 50},
//                 {id: 148, group: 50},
//                 {id: 149, group: 50},
//                 {id: 150, group: 50},
//                 {id: 319, group: 50},
//                 {id: 320, group: 50},
//                 {id: 321, group: 50},
//                 {id: 322, group: 50},
//                 {id: 323, group: 50},
//                 {id: 324, group: 50},
//                 {id: 325, group: 50},
//                 {id: 346, group: 50},
//                 {id: 347, group: 50},
//                 {id: 348, group: 50},
//                 {id: 349, group: 50},
//                 {id: 50, group: 50},
//               ],
//               links: [
//                 {
//                   source: 69,
//                   target: 50,
//                   value: 81.1,
//                 },
//                 {
//                   source: 70,
//                   target: 50,
//                   value: 79.1,
//                 },
//                 {
//                   source: 71,
//                   target: 50,
//                   value: 83.5,
//                 },
//                 {
//                   source: 73,
//                   target: 50,
//                   value: 95.5,
//                 },
//                 {
//                   source: 74,
//                   target: 50,
//                   value: 98.8,
//                 },
//                 {
//                   source: 145,
//                   target: 50,
//                   value: 84,
//                 },
//                 {
//                   source: 146,
//                   target: 50,
//       value: 94.1,
//     },
//     {
//       source: 319,
//       target: 50,
//       value: 78.6,
//     },
//     {
//       source: 320,
//       target: 50,
//       value: 83.6,
//     },
//     {
//       source: 321,
//       target: 50,
//       value: 83.8,
//     },
//     {
//       source: 322,
//       target: 50,
//       value: 86,
//     },
//     {
//       source: 323,
//       target: 50,
//       value: 84.5,
//     },
//     {
//       source: 324,
//       target: 50,
//       value: 94,
//     },
//     {
//       source: 325,
//       target: 50,
//       value: 99.8,
//     },
//     {
//       source: 346,
//       target: 50,
//       value: 80.1,
//     },
//     {
//       source: 347,
//       target: 50,
//       value: 95.3,
//     },
//     {
//       source: 348,
//       target: 50,
//       value: 86.5,
//     },
//     {
//       source: 349,
//       target: 50,
//       value: 99.9,
//     },
//   ],
// };

// graphData.nodes = graphData.nodes.concat ([
//   {
//     id: 52,
//     group: 51,
//   },
//   {
//     id: 53,
//     group: 51,
//   },
//   {
//     id: 54,
//     group: 51,
//   },
//   {
//     id: 55,
//     group: 51,
//   },
//   {
//     id: 56,
//     group: 51,
//   },
//   {
//     id: 58,
//     group: 51,
//   },
//   {
//     id: 59,
//     group: 51,
//   },
//   {
//     id: 60,
//     group: 51,
//   },
//   {
//     id: 61,
//     group: 51,
//   },
//   {
//     id: 62,
//     group: 51,
//   },
//   {
//     id: 63,
//     group: 51,
//   },
//   {
//     id: 66,
//     group: 51,
//   },
//   {
//     id: 67,
//     group: 51,
//   },
//   {
//     id: 68,
//     group: 51,
//   },
//   {
//     id: 130,
//     group: 51,
//   },
//   {
//     id: 131,
//     group: 51,
//   },
//   {
//     id: 132,
//     group: 51,
//   },
//   {
//     id: 133,
//     group: 51,
//   },
//   {
//     id: 134,
//     group: 51,
//   },
//   {
//     id: 135,
//     group: 51,
//   },
//   {
//     id: 136,
//     group: 51,
//   },
//   {
//     id: 137,
//     group: 51,
//   },
//   {
//     id: 138,
//     group: 51,
//   },
//   {
//     id: 139,
//     group: 51,
//   },
//   {
//     id: 140,
//     group: 51,
//   },
//   {
//     id: 141,
//     group: 51,
//   },
//   {
//     id: 142,
//     group: 51,
//   },
//   {
//     id: 143,
//     group: 51,
//   },
//   {
//     id: 152,
//     group: 51,
//   },
//   {
//     id: 153,
//     group: 51,
//   },
//   {
//     id: 154,
//     group: 51,
//   },
//   {
//     id: 155,
//     group: 51,
//   },
//   {
//     id: 156,
//     group: 51,
//   },
//   {
//     id: 157,
//     group: 51,
//   },
//   {
//     id: 307,
//     group: 51,
//   },
//   {
//     id: 309,
//     group: 51,
//   },
//   {
//     id: 310,
//     group: 51,
//   },
//   {
//     id: 311,
//     group: 51,
//   },
//   {
//     id: 312,
//     group: 51,
//   },
//   {
//     id: 313,
//     group: 51,
//   },
//   {
//     id: 314,
//     group: 51,
//   },
//   {
//     id: 315,
//     group: 51,
//   },
//   {
//     id: 316,
//     group: 51,
//   },
//   {
//     id: 317,
//     group: 51,
//   },
//   {
//     id: 318,
//     group: 51,
//   },
//   {
//     id: 326,
//     group: 51,
//   },
//   {
//     id: 327,
//     group: 51,
//   },
//   {
//     id: 328,
//     group: 51,
//   },
//   {
//     id: 330,
//     group: 51,
//   },
//   {
//     id: 332,
//     group: 51,
//   },
//   {
//     id: 333,
//     group: 51,
//   },
//   {
//     id: 334,
//     group: 51,
//   },
//   {
//     id: 335,
//     group: 51,
//   },
//   {
//     id: 336,
//     group: 51,
//   },
//   {
//     id: 337,
//     group: 51,
//   },
//   {
//     id: 338,
//     group: 51,
//   },
//   {
//     id: 339,
//     group: 51,
//   },
//   {
//     id: 341,
//     group: 51,
//   },
//   {
//     id: 343,
//     group: 51,
//   },
//   {
//     id: 351,
//     group: 51,
//   },
//   {
//     id: 352,
//     group: 51,
//   },
//   {
//     id: 354,
//     group: 51,
//   },
//   {
//     id: 355,
//     group: 51,
//   },
//   {
//     id: 356,
//     group: 51,
//   },
//   {id: 51, group: 51},
// ]);

// graphData.links = graphData.links.concat ([
//   {
//     source: 52,
//     target: 51,
//     value: 85.5,
//   },
//   {
//     source: 53,
//     target: 51,
//     value: 93.7,
//   },
//   {
//     source: 54,
//     target: 51,
//     value: 89,
//   },
//   {
//     source: 55,
//     target: 51,
//     value: 85.5,
//   },
//   {
//     source: 56,
//     target: 51,
//     value: 91.1,
//   },
//   {
//     source: 58,
//     target: 51,
//     value: 82.2,
//   },
//   {
//     source: 59,
//     target: 51,
//     value: 76.1,
//   },
//   {
//     source: 60,
//     target: 51,
//     value: 80.8,
//   },
//   {
//     source: 61,
//     target: 51,
//     value: 94.1,
//   },
//   {
//     source: 62,
//     target: 51,
//     value: 78.3,
//   },
//   {
//     source: 63,
//     target: 51,
//     value: 85.8,
//   },
//   {
//     source: 66,
//     target: 51,
//     value: 92.4,
//   },
//   {
//     source: 67,
//     target: 51,
//     value: 95.4,
//   },
//   {
//     source: 68,
//     target: 51,
//     value: 99.7,
//   },
//   {
//     source: 130,
//     target: 51,
//     value: 87.9,
//   },
//   {
//     source: 131,
//     target: 51,
//     value: 98.7,
//   },
//   {
//     source: 132,
//     target: 51,
//     value: 87.2,
//   },
//   {
//     source: 133,
//     target: 51,
//     value: 90.9,
//   },
//   {
//     source: 134,
//     target: 51,
//     value: 77.8,
//   },
//   {
//     source: 135,
//     target: 51,
//     value: 98.8,
//   },
//   {
//     source: 136,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 137,
//     target: 51,
//     value: 79.3,
//   },
//   {
//     source: 138,
//     target: 51,
//     value: 93.9,
//   },
//   {
//     source: 139,
//     target: 51,
//     value: 76.7,
//   },
//   {
//     source: 140,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 141,
//     target: 51,
//     value: 94.9,
//   },
//   {
//     source: 142,
//     target: 51,
//     value: 93.8,
//   },
//   {
//     source: 143,
//     target: 51,
//     value: 94.5,
//   },
//   {
//     source: 152,
//     target: 51,
//     value: 95.6,
//   },
//   {
//     source: 153,
//     target: 51,
//     value: 93.6,
//   },
//   {
//     source: 154,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 155,
//     target: 51,
//     value: 85.6,
//   },
//   {
//     source: 156,
//     target: 51,
//     value: 85.4,
//   },
//   {
//     source: 157,
//     target: 51,
//     value: 95.2,
//   },
//   {
//     source: 307,
//     target: 51,
//     value: 95.1,
//   },
//   {
//     source: 309,
//     target: 51,
//     value: 92.1,
//   },
//   {
//     source: 310,
//     target: 51,
//     value: 91.1,
//   },
//   {
//     source: 311,
//     target: 51,
//     value: 95.7,
//   },
//   {
//     source: 312,
//     target: 51,
//     value: 87.1,
//   },
//   {
//     source: 313,
//     target: 51,
//     value: 95.6,
//   },
//   {
//     source: 314,
//     target: 51,
//     value: 78.4,
//   },
//   {
//     source: 315,
//     target: 51,
//     value: 95,
//   },
//   {
//     source: 316,
//     target: 51,
//     value: 87.9,
//   },
//   {
//     source: 317,
//     target: 51,
//     value: 98.7,
//   },
//   {
//     source: 318,
//     target: 51,
//     value: 92.1,
//   },
//   {
//     source: 326,
//     target: 51,
//     value: 79,
//   },
//   {
//     source: 327,
//     target: 51,
//     value: 88.5,
//   },
//   {
//     source: 328,
//     target: 51,
//     value: 93.2,
//   },
//   {
//     source: 330,
//     target: 51,
//     value: 78,
//   },
//   {
//     source: 332,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 333,
//     target: 51,
//     value: 94.6,
//   },
//   {
//     source: 334,
//     target: 51,
//     value: 94.1,
//   },
//   {
//     source: 335,
//     target: 51,
//     value: 86.6,
//   },
//   {
//     source: 336,
//     target: 51,
//     value: 89,
//   },
//   {
//     source: 337,
//     target: 51,
//     value: 86.1,
//   },
//   {
//     source: 338,
//     target: 51,
//     value: 93.1,
//   },
//   {
//     source: 339,
//     target: 51,
//     value: 95.1,
//   },
//   {
//     source: 341,
//     target: 51,
//     value: 91,
//   },
//   {
//     source: 343,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 351,
//     target: 51,
//     value: 89.9,
//   },
//   {
//     source: 352,
//     target: 51,
//     value: 84.6,
//   },
//   {
//     source: 354,
//     target: 51,
//     value: 96.7,
//   },
//   {
//     source: 355,
//     target: 51,
//     value: 95.5,
//   },
//   {
//     source: 356,
//     target: 51,
//     value: 94.2,
//   },
//   {
//     source: 50,
//     target: 51,
//     value: 60,
//   },
// ]);

var c1 = {
  '50': {
    '69': 81.1,
    '70': 79.1,
    '71': 83.5,
    '73': 95.5,
    '74': 98.8,
    '145': 84,
    '146': 79.1,
    '148': 83.5,
    '149': 80.3,
    '150': 94.1,
    '319': 78.6,
    '320': 83.6,
    '321': 83.8,
    '322': 86,
    '323': 84.5,
    '324': 94,
    '325': 99.8,
    '346': 80.1,
    '347': 95.3,
    '348': 86.5,
    '349': 99.9,
  },
  '51': {
    '52': 85.5,
    '53': 93.7,
    '54': 89,
    '55': 85.5,
    '56': 91.1,
    '58': 82.2,
    '59': 76.1,
    '60': 80.8,
    '61': 94.1,
    '62': 78.3,
    '63': 85.8,
    '66': 92.4,
    '67': 95.4,
    '68': 99.7,
    '130': 87.9,
    '131': 98.7,
    '132': 87.2,
    '133': 90.9,
    '134': 77.8,
    '135': 98.8,
    '136': 95.5,
    '137': 79.3,
    '138': 93.9,
    '139': 76.7,
    '140': 95.5,
    '141': 94.9,
    '142': 93.8,
    '143': 94.5,
    '152': 95.6,
    '153': 93.6,
    '154': 95.5,
    '155': 85.6,
    '156': 85.4,
    '157': 95.2,
    '307': 95.1,
    '309': 92.1,
    '310': 91.1,
    '311': 95.7,
    '312': 87.1,
    '313': 95.6,
    '314': 78.4,
    '315': 95,
    '316': 87.9,
    '317': 98.7,
    '318': 92.1,
    '326': 79,
    '327': 88.5,
    '328': 93.2,
    '330': 78,
    '332': 95.5,
    '333': 94.6,
    '334': 94.1,
    '335': 86.6,
    '336': 89,
    '337': 86.1,
    '338': 93.1,
    '339': 95.1,
    '341': 91,
    '343': 95.5,
    '351': 89.9,
    '352': 84.6,
    '354': 96.7,
    '355': 95.5,
    '356': 94.2,
  },
  '57': {
    '64': 99.1,
    '65': 99.7,
    '151': 99.9,
    '308': 94.3,
    '329': 95.7,
    '331': 83.2,
    '340': 99.7,
    '342': 99.7,
    '353': 96.6,
  },
  '72': {
    '147': 86.8,
    '345': 86.1,
    '350': 92.7,
  },
  '144': {
    '344': 83.8,
  },
};
var nodes = Object.keys (c1).reduce ((a, c) => {
  const groupNodes = Object.keys (c1[c]).map (p => ({
    id: Number (p),
    group: Number (c),
  }));
  return [...a, ...groupNodes, {id: Number (c), group: Number (c)}];
}, []);

var links = Object.keys (c1).reduce ((a, c) => {
  const groupLinks = Object.keys (c1[c]).map (p => ({
    source: Number (p),
    target: Number (c),
    value: c1[c][p],
  }));
  return [...a, ...groupLinks];
}, []);

links = [
  ...links,
  ...Object.keys (c1).map ((c, i, arr) => {
    if (i + 1 < arr.length) {
      return {
        source: Number (c),
        value: 70,
        target: Number (arr[i + 1]),
      };
    } else {
      return {
        source: Number (c),
        value: 70,
        target: Number (arr[0]),
      };
    }
  }),
];
const graphData = {
  nodes,
  links,
};

// Get from the store
app.get ('/cluster/graph', (req, res) => {
  // res.set ('Access-Control-Allow-Origin', '*');
  const data = graphData;
  res.send (JSON.stringify (data));
});

// Set in the store
app.post ('/car/insurance', (req, res) => {
  console.log (req.body);
  // res.set ('Access-Control-Allow-Origin', '*');
  const data = graphData;
  res.send (JSON.stringify (data));
});

// Start the server
server.listen (8000, () => console.log ('Server is running!'));
